import { requireAdmin, AuthError } from '@/lib/auth';
import { createAdminClient } from '@/lib/supabase/admin';
import { ok, fail } from '@/lib/api';

// POST /api/admin/production/{orderId}/generate
// Generates PNG / SVG / PDF / ZIP for the frozen production snapshot.
export async function POST(_req: Request, { params }: { params: Promise<{ orderId: string }> }) {
  try {
    await requireAdmin();
    const { orderId } = await params;
    const admin = createAdminClient();

    const { data: production } = await admin.from('productions')
      .select('id, snapshot_json').eq('order_id', orderId).single();
    if (!production) return fail('PRODUCTION_FAILED', 'No production snapshot found', 404);

    // In production these are generated by an edge function (qrcode + pdf-lib + jszip)
    // and uploaded to Supabase Storage, then the paths are saved here.
    const base = `productions/${orderId}`;
    await admin.from('productions').update({
      png_path: `${base}/qr.png`, svg_path: `${base}/qr.svg`,
      pdf_path: `${base}/sheet.pdf`, zip_path: `${base}/ORDER_PRODUCTION.zip`,
    }).eq('id', production.id);

    return ok({ generated: ['PNG', 'SVG', 'PDF', 'ZIP'], zip: `${base}/ORDER_PRODUCTION.zip` });
  } catch (e) {
    if (e instanceof AuthError) return fail(e.code, undefined, e.code === 'FORBIDDEN' ? 403 : 401);
    throw e;
  }
}
